APP_ID="vaultwarden"
APP_NAME="Vaultwarden"
APP_DOMAIN="${VAULTWARDEN_DOMAIN}"
APP_PORT="${VAULTWARDEN_PORT}"
APP_EXTRA_PORTS="${VAULTWARDEN_NOTIFICATIONS_HUB_PORT}"
APP_CONTAINER="vaultwarden"
APP_TLS_NAME="vaultwarden"
APP_NGINX_ENABLED="true"
APP_CERTIFICATE_ENABLED="true"
APP_HEALTHCHECK_URL="http://${APP_DOMAIN}/alive"
