# Internal DNS names.
# Change these before installation if required.

FEDORA_DOMAIN="fedora-server.home"
PORTAINER_DOMAIN="portainer.home"
VAULTWARDEN_DOMAIN="vault.home"
PROXMOX_DOMAIN="proxmox.home"
