# Internal DNS names.
# Change these before installation if required.

PROXMOX_DOMAIN="proxmox.home"
FEDORA_DOMAIN="fedora-server.home"
PORTAINER_DOMAIN="portainer.home"
VAULTWARDEN_DOMAIN="vault.home"
JOPLIN_DOMAIN="joplin.home"
