APP_ID="portainer"
APP_NAME="Portainer CE"
APP_DOMAIN="${PORTAINER_DOMAIN}"
APP_PORT="${PORTAINER_PORT}"
APP_CONTAINER="portainer"
APP_TLS_NAME="portainer"
APP_NGINX_ENABLED="true"
APP_CERTIFICATE_ENABLED="true"
APP_HEALTHCHECK_URL="https://${APP_DOMAIN}/"
