APP_ID="joplin"
APP_NAME="Joplin Server"
APP_DOMAIN="${JOPLIN_DOMAIN}"
APP_PORT="${JOPLIN_PORT}"
APP_CONTAINER="joplin"
APP_TLS_NAME="joplin"
APP_NGINX_ENABLED="true"
APP_CERTIFICATE_ENABLED="true"
APP_HEALTHCHECK_URL="http://127.0.0.1:${JOPLIN_PORT}/"
