#!/usr/bin/env bash
set -Eeuo pipefail
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/00-common.sh"
require_root; require_fedora; load_config; load_domain_state; validate_config; ensure_dirs
[[ -f "$NETWORK_STATE" ]] || die 'Network state missing. Run the network stage first.'; source "$NETWORK_STATE"; valid_ipv4 "$STATIC_IP" || die "Invalid stored Fedora IP: $STATIC_IP"
[[ -f "$PROXMOX_STATE" ]] || die 'Proxmox state missing. Run the Proxmox stage first.'; source "$PROXMOX_STATE"; valid_ipv4 "$PROXMOX_IP" || die "Invalid stored Proxmox IP: $PROXMOX_IP"
selection_file="${STATE_DIR}/selected-apps.env"; selected_apps=''; [[ -f "$selection_file" ]] && { source "$selection_file"; selected_apps="${SELECTED_APPS:-}"; }
app_list(){ local a; declare -A seen=(); for a in $selected_apps; do seen["$a"]=1; printf '%s\n' "$a"; done; while IFS= read -r a; do [[ -n "$a" && -z "${seen[$a]:-}" ]] && app_is_installed "$a" && printf '%s\n' "$a"; done < <(app_ids); }
local_generate_ca(){ local k="${TLS_DIR}/ca.key" c="${TLS_DIR}/ca.crt"; [[ -s "$k" && -s "$c" ]] && return; log 'Generating local Certificate Authority'; openssl genrsa -out "$k" 4096; chmod 600 "$k"; openssl req -x509 -new -sha256 -key "$k" -out "$c" -days 3650 -subj '/C=XX/O=Home Lab/CN=Home Lab Local CA'; chmod 644 "$c"; }
local_generate_leaf(){ local n="$1" d="$2" ip="$3" k="${TLS_DIR}/${1}.key" c="${TLS_DIR}/${1}.crt" csr="${TLS_DIR}/${1}.csr" ext="${TLS_DIR}/${1}.ext"; printf 'basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\nsubjectAltName=DNS:%s,IP:%s\n' "$d" "$ip" > "$ext"; openssl genrsa -out "$k" 2048; openssl req -new -key "$k" -out "$csr" -subj "/C=XX/O=Home Lab/CN=${d}"; openssl x509 -req -in "$csr" -CA "${TLS_DIR}/ca.crt" -CAkey "${TLS_DIR}/ca.key" -CAcreateserial -out "$c" -days 365 -sha256 -extfile "$ext"; chmod 600 "$k"; chmod 644 "$c"; rm -f "$csr" "$ext" "${TLS_DIR}/ca.srl"; }
needs_regeneration(){ local c="$1" d="$2" ip="$3"; [[ -s "$c" ]] || return 0; openssl x509 -checkend $((30*86400)) -noout -in "$c" >/dev/null 2>&1 || return 0; openssl x509 -in "$c" -noout -ext subjectAltName | grep -Fq "DNS:${d}" || return 0; openssl x509 -in "$c" -noout -ext subjectAltName | grep -Fq "IP Address:${ip}" || return 0; return 1; }
legacy_names(){ local b="$1" p="${2%.}"; p="${p#.}"; if [[ -n "$p" ]]; then printf '%s\n' "fedora-server.${p}.${b}" "proxmox.${p}.${b}" "portainer.${p}.${b}" "vault.${p}.${b}" "joplin.${p}.${b}"; else printf '%s\n' "fedora-server.${b}" "proxmox.${b}" "portainer.${b}" "vault.${b}" "joplin.${b}"; fi; }
certbot_bin(){ [[ -x "${STACK_DIR}/certbot-venv/bin/certbot" ]] && { printf '%s' "${STACK_DIR}/certbot-venv/bin/certbot"; return; }; command -v certbot 2>/dev/null || true; }
certbot_delete(){ local n="$1" b; b="$(certbot_bin)"; [[ -n "$b" ]] && "$b" delete --cert-name "$n" --non-interactive >/dev/null 2>&1 || true; }
cleanup_legacy(){ local b="$1" p="$2"; log 'Cleaning managed legacy per-host Let’s Encrypt certificates'; while IFS= read -r n; do certbot_delete "$n"; done < <(legacy_names "$b" "$p"); }
if [[ -f "${STATE_DIR}/domain-previous.env" ]]; then current_mode="$DOMAIN_MODE"; current_base="$BASE_DOMAIN"; current_prefix="$APP_SUBDOMAIN"; current_email="${ACME_EMAIL:-}"; source "${STATE_DIR}/domain-previous.env"; old_mode="${DOMAIN_MODE:-}"; old_base="${BASE_DOMAIN:-}"; old_prefix="${APP_SUBDOMAIN:-home}"; [[ "$old_mode" == local ]] && find "$TLS_DIR" -mindepth 1 -maxdepth 1 -type f -delete 2>/dev/null || true; [[ "$old_mode" == public && -n "$old_base" ]] && { cleanup_legacy "$old_base" "$old_prefix"; old_zone="${old_prefix%.}"; old_zone="${old_zone#.}"; [[ -n "$old_zone" ]] && old_zone="${old_zone}.${old_base}" || old_zone="$old_base"; certbot_delete "$old_zone"; }; rm -f "${STATE_DIR}/domain-previous.env"; DOMAIN_MODE="$current_mode"; BASE_DOMAIN="$current_base"; APP_SUBDOMAIN="$current_prefix"; ACME_EMAIL="$current_email"; load_domain_state; fi
if [[ "$DOMAIN_MODE" == local ]]; then
 local_generate_ca
 while IFS= read -r a; do [[ -n "$a" ]] || continue; load_app_config "$a" || continue; [[ "${APP_CERTIFICATE_ENABLED:-true}" == true ]] || continue; c="${TLS_DIR}/${APP_TLS_NAME}.crt"; if needs_regeneration "$c" "$APP_DOMAIN" "$STATIC_IP"; then rm -f "${TLS_DIR}/${APP_TLS_NAME}.key" "$c"; local_generate_leaf "$APP_TLS_NAME" "$APP_DOMAIN" "$STATIC_IP"; fi; done < <(app_list)
 for item in "fedora-server:${FEDORA_DOMAIN}:${STATIC_IP}" "proxmox:${PROXMOX_DOMAIN}:${PROXMOX_IP}"; do IFS=: read -r n d ip <<< "$item"; c="${TLS_DIR}/${n}.crt"; needs_regeneration "$c" "$d" "$ip" && { rm -f "${TLS_DIR}/${n}.key" "$c"; local_generate_leaf "$n" "$d" "$ip"; }; done
 chmod 700 "$TLS_DIR"; chmod 600 "$TLS_DIR"/*.key; chmod 644 "$TLS_DIR"/*.crt; log "Local TLS material is ready in ${TLS_DIR}"; exit 0
fi
dnf install -y python3 python3-pip curl
CERTBOT_VENV="${STACK_DIR}/certbot-venv"; [[ -x "${CERTBOT_VENV}/bin/certbot" ]] || python3 -m venv "$CERTBOT_VENV"; "${CERTBOT_VENV}/bin/python" -m pip install --upgrade pip; "${CERTBOT_VENV}/bin/pip" install --upgrade certbot
CERTBOT="${CERTBOT_VENV}/bin/certbot"; godaddy_credentials_valid || die 'GoDaddy PAT is missing. Configure public mode again and provide a valid PAT.'; install -m 0750 "${REPO_ROOT}/scripts/godaddy-dns-hook.sh" "${STACK_DIR}/godaddy-dns-hook.sh"; chmod 700 "${STACK_DIR}/godaddy-dns-hook.sh"
APP_ZONE="${APP_SUBDOMAIN%.}"; APP_ZONE="${APP_ZONE#.}"; [[ -n "$APP_ZONE" ]] && APP_ZONE="${APP_ZONE}.${BASE_DOMAIN}" || APP_ZONE="$BASE_DOMAIN"; PUBLIC_CERT_NAME="$APP_ZONE"; PUBLIC_CERT_DIR="/etc/letsencrypt/live/${PUBLIC_CERT_NAME}"; cleanup_legacy "$BASE_DOMAIN" "$APP_SUBDOMAIN"
if [[ -s "${PUBLIC_CERT_DIR}/fullchain.pem" && -s "${PUBLIC_CERT_DIR}/privkey.pem" ]] && openssl x509 -checkend 86400 -noout -in "${PUBLIC_CERT_DIR}/fullchain.pem" >/dev/null 2>&1; then log "Wildcard certificate ${PUBLIC_CERT_NAME} already exists; renewal is handled by the systemd timer."; else log "Requesting one public ACME certificate for ${APP_ZONE} and *.${APP_ZONE}"; email_args=(); [[ -n "${ACME_EMAIL:-}" ]] && email_args=(--email "$ACME_EMAIL"); "$CERTBOT" certonly --manual --preferred-challenges dns --manual-auth-hook "${STACK_DIR}/godaddy-dns-hook.sh auth" --manual-cleanup-hook "${STACK_DIR}/godaddy-dns-hook.sh cleanup" --non-interactive --agree-tos "${email_args[@]}" --keep-until-expiring --cert-name "$PUBLIC_CERT_NAME" -d "$APP_ZONE" -d "*.${APP_ZONE}"; fi
log "Public wildcard TLS material is ready under ${PUBLIC_CERT_DIR}/"
